/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 banespa.gltf --transform 
Files: banespa.gltf [8.36MB] > /Users/fmammoli/Developer/sp-diorama-gallery/banespa-transformed.glb [556.16KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function BanespaSimp(props) {
  const { nodes, materials } = useGLTF("/banespa-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.material_0} />
    </group>
  );
}

useGLTF.preload("/banespa-transformed.glb");
