/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 copan_simp.gltf --transform 
Files: copan_simp.gltf [12.11MB] > /Users/fmammoli/Developer/sp-diorama-gallery/copan_simp-transformed.glb [839.96KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CopanSimp(props) {
  const { nodes, materials } = useGLTF("/copan_simp-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.material_0} />
    </group>
  );
}

useGLTF.preload("/copan_simp-transformed.glb");
