/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 masp.gltf --transform 
Files: masp.gltf [7.01MB] > /Users/fmammoli/Developer/sp-diorama-gallery/masp-transformed.glb [375.88KB] (95%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Masp(props) {
  const { nodes, materials } = useGLTF("/masp-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.material_0} />
    </group>
  );
}

useGLTF.preload("/masp-transformed.glb");
