/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 pavilhao_japones.gltf --transform 
Files: pavilhao_japones.gltf [4.92MB] > /Users/fmammoli/Developer/sp-diorama-gallery/pavilhao_japones-transformed.glb [295.17KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PavilhaoJaponesSimp(props) {
  const { nodes, materials } = useGLTF("/pavilhao_japones-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.material_0} />
    </group>
  );
}

useGLTF.preload("/pavilhao_japones-transformed.glb");
