/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 sesc_paulista.gltf --transform 
Files: sesc_paulista.gltf [8.53MB] > /Users/fmammoli/Developer/sp-diorama-gallery/sesc_paulista-transformed.glb [562.58KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SescPaulistaSimp(props) {
  const { nodes, materials } = useGLTF("/sesc_paulista-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.material_0} />
    </group>
  );
}

useGLTF.preload("/sesc_paulista-transformed.glb");
